trigger:
  branches:
    include:
    - master
    - develop
    - 'v?.*'
    - 'validate/*'
  paths:
    exclude: ["doc", "*.md"]

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU

stages:
- stage: Build
  jobs:
  - job: Unity
    pool:
      name: CustomAgents
      demands: UNITYHUB_EDITORS_FOLDER_LOCATION
    steps:
    - checkout: self
      clean: true
    - template: azure-pipelines/install-dependencies.yml
    - template: azure-pipelines/build_unity.yml
